<?xml version="1.0" encoding="utf-8"?><testsuite errors="2" failures="1" name="pytest" skipped="0" tests="3" time="0.154"><testcase classname="test_case01.Test_Case" file="test_case01.py" line="19" name="test_case" time="0.003"><error message="test setup failure">request = &lt;SubRequest &apos;haha&apos; for &lt;Function test_case&gt;&gt;

    @pytest.fixture(scope=&apos;class&apos;)
    def haha(request):
        print(&apos;开始测试&apos;)
        #a = &apos;5&apos;
&gt;       a = request.param[&apos;a&apos;]
E       AttributeError: &apos;SubRequest&apos; object has no attribute &apos;param&apos;

test_case01.py:11: AttributeError</error><system-out>开始测试
</system-out></testcase><testcase classname="test_case01.Test_Case" file="test_case01.py" line="25" name="test_case2" time="0.000"><error message="test setup failure">request = &lt;SubRequest &apos;haha&apos; for &lt;Function test_case&gt;&gt;

    @pytest.fixture(scope=&apos;class&apos;)
    def haha(request):
        print(&apos;开始测试&apos;)
        #a = &apos;5&apos;
&gt;       a = request.param[&apos;a&apos;]
E       AttributeError: &apos;SubRequest&apos; object has no attribute &apos;param&apos;

test_case01.py:11: AttributeError</error></testcase><testcase classname="test_case01.Test_Case" file="test_case01.py" line="28" name="test_case3" time="0.001"><failure message="AssertionError: 不是1
assert &apos;2&apos; == &apos;1&apos;
  - 2
  + 1">self = &lt;package_test.l_pytest.test_case01.Test_Case object at 0x04576BB0&gt;

    def test_case3(self):
&gt;       assert &apos;2&apos; == &apos;1&apos;, &apos;不是1&apos;
E       AssertionError: 不是1
E       assert &apos;2&apos; == &apos;1&apos;
E         - 2
E         + 1

test_case01.py:30: AssertionError</failure></testcase></testsuite>